# Generated by Django 6.0.5 on 2026-05-25 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_seed_initial_tests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ студента')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='practice_submissions/%Y/%m/', verbose_name='Прикреплённый файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.practicetask', verbose_name='Практическое задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправка практической работы',
                'verbose_name_plural': 'Отправки практических работ',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'task'), name='unique_practice_submission_per_user')],
            },
        ),
    ]
