# Generated by Django 6.0.5 on 2026-05-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_practicesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('selected_answer_text', models.CharField(blank=True, max_length=255, verbose_name='Текст выбранного ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ответ верный')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='learning.testattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='learning.question', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_answers', to='learning.answer', verbose_name='Выбранный ответ')),
            ],
            options={
                'verbose_name': 'Ответ в попытке теста',
                'verbose_name_plural': 'Ответы в попытках тестов',
                'ordering': ['attempt', 'question__order', 'id'],
            },
        ),
    ]
