# Generated by Django 6.0.5 on 2026-05-26 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_testattemptanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetest',
            name='passing_percent',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Проходной процент'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент выполнения'),
        ),
    ]
